[program:opd32b-eval]
environment=PROC_NAME="%(program_name)s"
command=/opt/supervisor-scripts/opd32b-eval.sh
autostart=false
autorestart=unexpected
startsecs=5
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/stdout
redirect_stderr=true
stdout_logfile_maxbytes=0
stopsignal=TERM
